[project]
name = "ica-project"
version = "0.1.0"
description = "Deep learning for immigrant collective action classification."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "tensorflow-metal; sys_platform == 'darwin'",
  "tensorflow[and-cuda]; sys_platform == 'linux'",
  "tensorflow-text",
  "keras",
  "keras_hub",
  "numpy",
  "polars",
  # "cvxopt>=1.3.2", # these are only needed if we decide to use
  # "scipy>=1.16.3", # the Ramaswamy et al 2016 prior estimation method
  "scikit-learn>=1.7.2",
  "scipy>=1.16.3",
  "pandas>=2.3.3",
]
